// For Product Reducer
export const SET_PRODUCTS = "SET_PRODUCTS"
// export const SET_FEATURED_PRODUCTS = "SET_FEATURED_PRODUCTS"
// export const SET_POPULAR_PRODUCTS = "SET_POPULAR_PRODUCTS"
export const SET_SELECTED_PRODUCTS = "SET_SELECTED_PRODUCTS"
export const TOGGLE_OPEN_MODEL = "TOGGLE_OPEN_MODEL"
export const SET_FILTERED_PRODUCT = "SET_FILTERED_PRODUCT"
export const SET_ERROR = "SET_ERROR"
export const SET_VISITED_PRODUCT = "SET_VISITED_PRODUCT"
export const SET_PRODUCT_QTY = "SET_PRODUCT_QTY"

// For Cart Reducer
export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const SET_CART_PRODUCT_QTY = "SET_CART_PRODUCT_QTY"
export const TOGGLE_ADDED_TO_CART = "TOGGLE_ADDED_TO_CART"

// For Orders Reducer
export const TOGGLE_LOADING = "TOGGLE_LOADING"
export const SET_ORDERS = "SET_ORDERS"
export const TOGGLE_ORDER_SUBMITTED = "TOGGLE_ORDER_SUBMITTED"
export const SET_ORDER_ERROR = "SET_ORDER_ERROR"

// For Auth Reducer
export const TOGGLE_AUTH_LOADING = 'TOGGLE_AUTH_LOADING'
export const SET_AUTH_DATA = 'SET_AUTH_DATA'
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const TOGGLE_CHECKOUT_CLICKED = "TOGGLE_CHECKOUT_CLICKED"
